version: '3.7'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4.5
    restart: always
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_ENABLE_SNMP_TRAPS: 'false'  # Включить, если нужны SNMP-трапсы
    volumes:
      - zbx-data:/var/lib/zabbix
    depends_on:
      - db
    ports:
      - "10051:10051"
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.5
    restart: always
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow  # Убедитесь, что указана правильная временная зона
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4.5
    restart: always
    environment:
      ZBX_SERVER_HOST: "10.162.102.8"
      ZBX_SERVER_PORT: "10051"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

volumes:
  db-data:
  zbx-data:

networks:
  zabbix-network:
    driver: bridge
