version: '3.7'

services:
#Разворачиваем базу данных для Zabbix (в данном случае использую Postgress)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - zabbix-network
#Разворачиваем непосредственно Zabbix-Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4.5
    restart: always
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_ENABLE_SNMP_TRAPS: 'false'  # Включить, если нужны ловушки SNMP
    volumes:
      - zbx-data:/var/lib/zabbix
    depends_on:
#Ставим зависимость от запуска Базы данных
      - db
    ports:
      - "10051:10051"
    networks:
      - zabbix-network
#Разворачиваем Web-console для zabbix-sedrver
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.5
    restart: always
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
# Устанавливаем зависимость от запуска zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-network

# Zabbix-agent 
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4.5
    restart: always
    environment:
#Указываем IP адрес сервера для агента, и его порт
      ZBX_SERVER_HOST: "*.*.*.*"
      ZBX_SERVER_PORT: "10051"
#Ставим зависимость для агента, запуск после Zabbix-сервера
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

volumes:
  db-data:
  zbx-data:

networks:
  zabbix-network:
    driver: bridge
